// Code generated by Wire. DO NOT EDIT.（生成器依赖暂未入 go.sum——按 wire 语义手工同步，
// 与 wire.go 集合保持一致；排序与 zhuzhao wire_gen 风格对齐）

//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/tracerbiubiubiu/taskrunner/internal/config"
)

func InitializeApp(cfg *config.Config) (*App, func(), error) {
	logger := provideLogger(cfg)
	redisOpt := provideRedisOpt(cfg)
	store, cleanup1, err := provideStore(cfg)
	if err != nil {
		return nil, nil, err
	}
	submitter := provideSubmitter(cfg, store, redisOpt)
	inspector := provideInspector(redisOpt)
	taskService := provideTaskService(cfg, store, submitter, inspector)
	cronLoop := provideCron(cfg, store, submitter, logger)
	asynqServer, cleanup2, err := provideAsynqServer(cfg, redisOpt, logger)
	if err != nil {
		cleanup1()
		return nil, nil, err
	}
	callbackClient := provideCallback(cfg)
	keys := provideKeys(cfg)
	ready := provideReadyz(cfg, store)
	engine := provideEngine(taskService, keys, ready, logger)
	app := NewApp(cfg, logger, engine, asynqServer, cronLoop, store, callbackClient)
	return app, func() {
		cleanup2()
		cleanup1()
	}, nil
}
